### ISSUE TITLE
Ideas for further developement

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/nice-sbt-settings#16]
Short-term improvements:
- [x] update literator and taglist plugins (unicode bugfix)
- [x] change log-level for `FIXME` tags to error and ask/stop if there are some
- [x] ask to continue after `tagList`
- [x] fix: error messages instead of exceptions
- [x] fix: `pushApiDocsToGHPagesAction` check vcs operations like remote fetching

General improvements:
- ~~simple substitution of the actual version in README~~ ( there was a plugin for something like that, but it's outdated and it's too simple to use a special plugin)
- ~~_maybe_ using [sbt-git](https://github.com/sbt/sbt-git) or directly jgit instead of pretty fragile git invocations through `sys.process`~~ (sbt-git is quite crappy and we have everything we need related to git in a DSL implemented in #42)
- [x] better api docs generation:
  - [x] check gh-pages branch existence; mb create it if needed
  - [x] create/update `latest/api` link(?) on release

Integrating more plugins:
- ~~notes.imlicit.ly integration: [herald](https://github.com/n8han/herald)~~ (we have now our own [sbt-github-release](https://github.com/ohnosequences/sbt-github-release) for publishing notes to Github Releases)
- [bintray-sbt](https://github.com/softprops/bintray-sbt) for releases on bitray
  - latest working implementation is in https://github.com/ohnosequences/ivy-s3-resolver/pull/6/files. It's easy, but I don't see a way to publish both to Bintray and our S3:
  - ~~[sbt-multi-publish](https://github.com/davidharcombe/sbt-multi-publish) can be useful, if we want to publish both to our own repositories and bintray~~ (it's totally outdated and I don't see any alternative)
- packaging/distributing:
  - [sbt-proguard](https://github.com/sbt/sbt-proguard) — _maybe_ we should switch to it from sbt-assembly for fat jars, because it can reduce their size and do some other tricks
  - [sbt-pack](https://github.com/xerial/sbt-pack) — looks fine; in active developement
  - [sbt-native-packager](https://github.com/sbt/sbt-native-packager) — may be the best option, but the state of the project is unclear
  - ~~just for note: [travisci-sbt-packaging](https://github.com/michaelklishin/travisci-sbt-packaging) — fancy travis stuff...~~
- documentation related:
  - [sbt-site](https://github.com/sbt/sbt-site) — note [this](https://github.com/sbt/sbt-site#scaladoc-apis)
  - there are several more site generators for sbt, but I think this all is more related to improving literator sbt-plugin; also [laika](http://planet42.github.io/Laika/using-laika/sbt.html) looks the most interesting for me here
- codestyle/linting:
    - [x] [wartremover](https://github.com/typelevel/wartremover)
    - [ ] [scalastyle-sbt-plugin](https://github.com/scalastyle/scalastyle-sbt-plugin)
    - [ ] [jorgeortiz85/linter](https://github.com/jorgeortiz85/linter)
    - [ ] scalafmt (see #59)
- don't know if it can be useful, but maybe integrate some static code analysis plugins:
  - [sbt-stats](https://github.com/orrsella/sbt-stats) — just some curios info, maybe useless
  - [cpd4sbt](https://github.com/sbt/cpd4sbt) — PMD's Copy/Paste Detector; I'd like to run it on the bio4j java code :trollface:
  - [findbugs4sbt](https://github.com/sbt/findbugs4sbt) — similar; only for java

**Comment by eparejatobes** [comment]
closing?

**Comment by laughedelic** [comment]
No, updating 😉

**Comment by laughedelic** [comment]
I updated the original post and here are current ideas for short-term changes:

- [ ] drop literator and start actively using ScalaDoc #62 
- [ ] integrate Scalafmt for automatic code formatting #59 
- [ ] publish opensource things to Bintray _in addition_ to our own S3 (not resolved yet, see https://github.com/sbt/sbt-bintray/issues/131)

**Comment by eparejatobes** [comment]
> publish opensource things to Bintray in addition to our own S3

Is bintray kind of standard, or is still some fringe thing? what are the default sbt resolvers in 1.0? I would like to publish to somewhere resolvable by default.

**Comment by laughedelic** [comment]
> Is bintray kind of standard, or is still some fringe thing? what are the default sbt resolvers in 1.0? I would like to publish to somewhere resolvable by default.

Well, then Bintray is a good place, because it's included in default resolvers **since sbt 0.13.6**. I think it is considered standard.
